--CHAVE PRIMARIA 
--CLIENTE 

ALTER TABLE PESSOA
ADD CONSTRAINT PK_PESSOA
PRIMARY KEY (id_pessoa);

ALTER TABLE CLI_FISICO
ADD CONSTRAINT PK_CLI_FISICO
PRIMARY KEY(cpf_cli);

ALTER TABLE CLI_JURIDICO
ADD CONSTRAINT PK_CLI_JURIDICO
PRIMARY KEY(cnpj_cli);

ALTER TABLE DERPART_CONTATO_CLI
ADD CONSTRAINT PK_DERPART_CONTATO_CLI
PRIMARY KEY(id_contato);


--DADOS PESSOAIS

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO
PRIMARY KEY(id_end);


ALTER TABLE LOGRADOURO
ADD CONSTRAINT PK_LOGRADOURO
PRIMARY KEY(cep_logra);

ALTER TABLE BAIRRO
ADD CONSTRAINT PK_BAIRRO
PRIMARY KEY(id_bairro);

ALTER TABLE CIDADE
ADD CONSTRAINT PK_CIDADE
PRIMARY KEY(id_cid);

ALTER TABLE TELEFONE_PESSOA
ADD CONSTRAINT PK_TELEFONE_PESSOA
PRIMARY KEY(id_tel);

ALTER TABLE EMAIL_PESSOA
ADD CONSTRAINT PK_EMAIL_PESSOA
PRIMARY KEY(id_email);
--PEDIDO

ALTER TABLE COMPRADOR
ADD CONSTRAINT PK_COMPRADOR
PRIMARY KEY(id_comprador);

ALTER TABLE PAGAMENTO
ADD CONSTRAINT PK_PAGAMENTO
PRIMARY KEY(id_pag);

ALTER TABLE PEDIDO 
ADD CONSTRAINT PK_PEDIDO 
PRIMARY KEY(num_ped);

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_PRODUTO
PRIMARY KEY(ref_prod);
--FORNECEDOR
ALTER TABLE FORNECEDORES
ADD CONSTRAINT PK_FORNECEDORES
PRIMARY KEY(id_fornecedor);
