-- CHAVES ESTRANGEIRAS

ALTER TABLE CLI_FISICO
ADD CONSTRAINT FK_CLI_FISICO_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES PESSOA(id_pessoa);

ALTER TABLE CLI_JURIDICO
ADD CONSTRAINT FK_CLI_JURIDICO_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES  PESSOA(id_pessoa);

ALTER TABLE DERPART_CONTATO_CLI
ADD CONSTRAINT FK_DERPART_CONTATO_CLI_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES PESSOA(id_pessoa);
--DADOS PESSOAIS

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES PESSOA(id_pessoa);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_TIPO_ENDERECO
FOREIGN KEY (tipo_end)
REFERENCES TIPO_ENDERECO(tipo_end);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_LOGRADOURO
FOREIGN KEY (cep_logra)
REFERENCES LOGRADOURO(cep_logra);

ALTER TABLE LOGRADOURO
ADD CONSTRAINT FK_LOGRADOURO_BAIRRO
FOREIGN KEY (id_bairro)
REFERENCES BAIRRO (id_bairro);

ALTER TABLE BAIRRO
ADD CONSTRAINT FK_BAIRRO_CIDADE
FOREIGN KEY (id_cid)
REFERENCES CIDADE (id_cid);

ALTER TABLE TELEFONE_PESSOA
ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES PESSOA (id_pessoa);

ALTER TABLE EMAIL_PESSOA
ADD CONSTRAINT FK_EMAIL_PESSOA
FOREIGN KEY (id_pessoa)
REFERENCES PESSOA (id_pessoa);

--PEDIDO

ALTER TABLE PEDIDO 
ADD CONSTRAINT FK_PEDI_JURIDICO
FOREIGN KEY (cnpj_cli)
REFERENCES CLI_JURIDICO (cnpj_cli);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDI_FISICO
FOREIGN KEY (cpf_cli)
REFERENCES CLI_FISICO (cpf_cli);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PAGAMENTO_FORNECEDORES
FOREIGN KEY (id_fornecedor)
REFERENCES FORNECEDORES (id_fornecedor);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PAGAMENTO_COMPRADOR
FOREIGN KEY (id_comprador)
REFERENCES COMPRADOR (id_comprador);

ALTER TABLE PAGAMENTO_PEDIDO
ADD CONSTRAINT FK_PEDIDO_PAGAMENTO
FOREIGN KEY (num_ped)
REFERENCES PEDIDO (num_ped);

ALTER TABLE PAGAMENTO_PEDIDO
ADD CONSTRAINT FK_PAGAMENTO_PEDIDO
FOREIGN KEY (id_pag)
REFERENCES PAGAMENTO(id_pag);

ALTER TABLE PEDIDO_PRODUTO
ADD CONSTRAINT FK_PRODUTO_PEDIDO
FOREIGN KEY (ref_prod)
REFERENCES PRODUTO(ref_prod);

ALTER TABLE PEDIDO_PRODUTO
ADD CONSTRAINT FK_PEDIDO_PRODUTO
FOREIGN KEY (num_ped)
REFERENCES PEDIDO(num_ped);


ALTER TABLE PRODUTO
ADD CONSTRAINT FK_PRODUTO_FORNECEDORES
FOREIGN KEY (id_fornecedor)
REFERENCES FORNECEDORES (id_fornecedor);

ALTER TABLE FORNECEDORES
ADD CONSTRAINT FK_FORNECEDORES_PESSOAS
FOREIGN KEY (id_pessoa)
REFERENCES  PESSOA (id_pessoa);